"""add account_state to users

Revision ID: 96700cb85b61
Revises: cacd5554ba5a
Create Date: 2026-05-06 19:33:12.887144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96700cb85b61'
down_revision: Union[str, None] = 'cacd5554ba5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type manually for PostgreSQL
    sa.Enum('VERIFIED', 'UNVERIFIED', 'INCOMPLETE_ONBOARDING', name='accountstate').create(op.get_bind())

    # Add account_state column with server_default for existing rows
    op.add_column('users', sa.Column(
        'account_state', 
        sa.Enum('VERIFIED', 'UNVERIFIED', 'INCOMPLETE_ONBOARDING', name='accountstate'), 
        server_default='UNVERIFIED', 
        nullable=False
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_state')

    # Drop the Enum type manually
    sa.Enum('VERIFIED', 'UNVERIFIED', 'INCOMPLETE_ONBOARDING', name='accountstate').drop(op.get_bind())
    # ### end Alembic commands ###
