"""add email to WaitlistSignup

Revision ID: ed6aad565b56
Revises: c6ef36577539
Create Date: 2026-05-13 16:37:55.167630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed6aad565b56'
down_revision: Union[str, None] = 'c6ef36577539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_signups', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'waitlist_signups', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist_signups', type_='unique')
    op.drop_column('waitlist_signups', 'email')
    # ### end Alembic commands ###
